var teams =
[
  { num:1, title:'none', teamname:'none', reviewers:[]},
  { num:2, title:'none', teamname:'none', reviewers:[]},
  { num:3, title:'none', teamname:'none', reviewers:[]},
  { num:4,
    title:'Totoro',
    teamname:'Totoro',
    reviewers:[], 
    url:"https://sites.google.com/a/brandeis.edu/totoro/finalgame"},
  { num:5,
    title:'Pokemon World',
    teamname:'LandWorks',
    reviewers:[], 
    url:"https://sites.google.com/a/brandeis.edu/cs164a-fall16/homework/hw9"},
  { num:6, title:'none', teamname:'none', reviewers:[]},
  { num:7, title:'none', teamname:'none', reviewers:[]},
  { num:8, title:'none', teamname:'none', reviewers:[]},
  { num:9, title:'none', teamname:'none', reviewers:[]},
  { num:10,
    title:'Cat Assassin',
    teamname:'Team Ten',
    reviewers:[], 
    url:"https://sites.google.com/a/brandeis.edu/cat-assassin/home/rc1"},
  { num:11, title:'none', teamname:'none', reviewers:[]},
  { num:12, title:'none', teamname:'none', reviewers:[]},
  { num:13,
    title:'Superman Travelling the Sky',
    teamname:'Forensic Heroes',
    reviewers:[], 
    url:"https://sites.google.com/a/brandeis.edu/forensic-heroes/cr1"},
  { num:14, title:'none', teamname:'none', reviewers:[]},
  { num:15, title:'none', teamname:'none', reviewers:[]},
  { num:16, title:'none', teamname:'none', reviewers:[]},
  { num:17, title:'none', teamname:'none', reviewers:[]},
  { num:18, title:'none', teamname:'none', reviewers:[]},
  { num:19, title:'none', teamname:'none', reviewers:[]},
  { num:20, title:'none', teamname:'none', reviewers:[]},
  { num:21, title:'none', teamname:'none', reviewers:[]},
  { num:22, title:'none', teamname:'none', reviewers:[]},
  { num:23, title:'none', teamname:'none', reviewers:[]},
  { num:24, title:'none', teamname:'none', reviewers:[]},
  { num:25, title:'none', teamname:'none', reviewers:[]},
  { num:26, title:'none', teamname:'none', reviewers:[]},
  { num:27, title:'none', teamname:'none', reviewers:[]},
  { num:28, title:'none', teamname:'none', reviewers:[]},
  { num:29,
    title:'SuperApple',
    teamname:'SuperNova',
    reviewers:[], 
    url:"https://sites.google.com/a/brandeis.edu/supernova/rc1"},
  { num:30, title:'none', teamname:'none', reviewers:[]},
  { num:31, title:'none', teamname:'none', reviewers:[]},
  { num:32, title:'none', teamname:'none', reviewers:[]}
];

var members =
[
  {team:0, name:"Acharya, Nishan",	email:"acharyan@brandeis.edu"},
{team:0, name:"Alvarado, Joshua",	email:"jalva@brandeis.edu"},
{team:0, name:"Amrien, Conor",	email:"	rconora@brandeis.edu"},
{team:0, name:"April, Nicholas",	email:"	napril@brandeis.edu"},
{team:0, name:"Berkowitz, Adi",	email:"	adiberk@brandeis.edu"},
{team:0, name:"Brown, Brianna",	email:"	bb3048@brandeis.edu"},
{team:0, name:"Browning, Beckett",	email:"beckettb@brandeis.edu"},
{team:0, name:"Bug, Moses",	email:"	mbug@brandeis.edu"},
{team:0, name:"Byun, Jin",	email:"	byunjins@brandeis.edu"},
{team:0, name:"Cabrera, Paul",	email:"	pcabrera@brandeis.edu"},
{team:5, name:"Chen, Bruce",	email:"Siyu	brucewilliam@brandeis.edu"},
{team:0, name:"Chen, Jacky",	email:"sychen1996@brandeis.edu"},
{team:0, name:"Chen, Jialong",	email:"jlch@brandeis.edu"},
{team:4, name:"Chen, Lian",	email:"lianc@brandeis.edu"},
{team:0, name:"Chen, Steven",	email:"stevenchen@brandeis.edu"},
{team:0, name:"Chen, Steven",	email:"stchen10@brandeis.edu"},
{team:0, name:"Chen, Xi",	email:"shibu@brandeis.edu"},
{team:29, name:"Chen, Yujin",	email:"ychen02@brandeis.edu"},
{team:0, name:"Cohen, Gerrianna",	email:"gerri@brandeis.edu"},
{team:13, name:"Cooper, Jordan",	email:"	jcoop@brandeis.edu"},
{team:0, name:"Costrell, Sarah",	email:"	costrell@brandeis.edu"},
{team:0, name:"Cruz, Angel",	email:"	acruz146@brandeis.edu"},
{team:0, name:"Cui, Zimu",	email:"	czm0821@brandeis.edu"},
{team:0, name:"Davis, Hannah",	email:"	hdavis20@brandeis.edu"},
{team:0, name:"Davis, Justus",	email:"	jkdavis@brandeis.edu"},
{team:5, name:"Di, Fan",	email:"		fdi@brandeis.edu"},
{team:0, name:"Dolgopolskaia, Polina",	email:"polinad@brandeis.edu"},
{team:0, name:"Dong, Xinhang",	email:"frankdong@brandeis.edu"},
{team:10, name:"Du, Han",	email:"	carinadu@brandeis.edu"},
{team:0, name:"Du, Yuheng",	email:"adu36@brandeis.edu"},
{team:0, name:"Ellis, Rosalind",	email:"rnellis@brandeis.edu"},
{team:0, name:"Fan, Jiayi",	email:"floria0126@brandeis.edu"},
{team:0, name:"Fang, Laury",	email:"lauryfhy@brandeis.edu"},
{team:0, name:"Figueroa, Andrews",	email:"andrews9008@brandeis.edu"},
{team:0, name:"Finamore, Lorenzo",	email:"lorenzo8@brandeis.edu"},
{team:0, name:"Frymark, Derek",	email:"	dfrymark@brandeis.edu"},
{team:29, name:"Gao, Chenxi",	email:"	gaoc@brandeis.edu"},
{team:0, name:"Geng, Jiapeng",	email:"	sethgeng@brandeis.edu"},
{team:0, name:"Givner, Ari",	email:"	agivner@brandeis.edu"},
{team:13, name:"Goldberg, Joshua",	email:"jsgberg@brandeis.edu"},
{team:0, name:"Goncalves, Alyssa",	email:"amgoncalves@brandeis.edu"},
{team:0, name:"Goncalves Dos Santos, Vanio",	email:"vanio@brandeis.edu"},
{team:0, name:"Grover, Priyanka",	email:"priyankagrover@brandeis.edu"},
{team:29, name:"Guan, Rong",	email:"	rguan@brandeis.edu"},
{team:0, name:"Guo, Yutong",	email:"	tonyguo@brandeis.edu"},
{team:0, name:"Hacala, Edward",	email:"	eshacala@brandeis.edu"},
{team:0, name:"Hall, Mercedes",	email:"	mercedes@brandeis.edu"},
{team:0, name:"Helas, David",	email:"	dhelas09@brandeis.edu"},
{team:4, name:"Hu, Yuling",	email:"	huyuling@brandeis.edu"},
{team:0, name:"Huang, Nicole",	email:"	nhuang@brandeis.edu"},
{team:0, name:"Ibas, Beraa",	email:"	bibas@brandeis.edu"},
{team:0, name:"Jeong, Sean",	email:"	seanje@brandeis.edu"},
{team:0, name:"Jiang, Michael",	email:"	mjiang@brandeis.edu"},
{team:4, name:"Jiao, Xiaoling",	email:"	xjiao@brandeis.edu"},
{team:5, name:"Jin, Mingyang",	email:"	mingyang1994@brandeis.edu"},
{team:0, name:"Kao, Geoffrey",	email:"	gkao123@brandeis.edu"},
{team:0, name:"Khimjee, Sarah",	email:"	sarahkhimjee@brandeis.edu"},
{team:0, name:"Kimmel, Danny",	email:"	kimmel95@brandeis.edu"},
{team:0, name:"Lavrentyeva, Sofia",	email:"slavren@brandeis.edu"},
{team:0, name:"Lee, Andrew",	email:"leeancho@brandeis.edu"},
{team:0, name:"Lee, Brian",	email:"egwoo@brandeis.edu"},
{team:0, name:"Lee, Leah",	email:"dasollee@brandeis.edu"},
{team:0, name:"Lee, Marcus",	email:"leemarcusmz@brandeis.edu"},
{team:0, name:"Lee, Vincent",	email:"vincelee@brandeis.edu"},
{team:0, name:"Lei, Shuyi",	email:"kellylei@brandeis.edu"},
{team:0, name:"Li, Borui",	email:"borui@brandeis.edu"},
{team:0, name:"Li, Jiewen",	email:"jiewenli@brandeis.edu"},
{team:0, name:"Li, Macy",	email:"macy0805@brandeis.edu"},
{team:0, name:"Li, Yanlin",	email:"rachelli@brandeis.edu"},
{team:0, name:"Liang, Angela",	email:"angella1996@brandeis.edu"},
{team:0, name:"Lin, Sylvia",	email:"sblin@brandeis.edu"},
{team:0, name:"Liu, Chao",	email:"lc89757@brandeis.edu"},
{team:13, name:"Lo, Ed",	email:"	edlo@brandeis.edu"},
{team:0, name:"Longfellow, Jeremy",	email:"sachio@brandeis.edu"},
{team:4, name:"Lu, Runjie",	email:"lurunjie@brandeis.edu"},
{team:13, name:"Lu, Siyuan",	email:"eutopia@brandeis.edu"},
{team:0, name:"Ma, Cindy",	email:"cindym@brandeis.edu"},
{team:0, name:"Marks, Aaron",	email:"marksaaron@brandeis.edu"},
{team:0, name:"Moncaleano, Maria",	email:"marm@brandeis.edu"},
{team:0, name:"Moon, Sung",	email:"Jun		moonms1@brandeis.edu"},
{team:10, name:"Nie, Shuyuan",	email:"	blackmew@brandeis.edu"},
{team:0, name:"Nineberg, Sam",	email:"	sabird1@brandeis.edu"},
{team:13, name:"Novas, John",	email:"	jnovas@brandeis.edu"},
{team:0, name:"Owens, Quay",	email:"	quay@brandeis.edu"},
{team:0, name:"Park, Chanwoo",	email:"	parkchan@brandeis.edu"},
{team:0, name:"Perez, Irving",	email:"	irvingperez@brandeis.edu"},
{team:0, name:"Pham, Vi",	email:"	knopewecan@brandeis.edu"},
{team:0, name:"Pinilla, Jay",	email:"	jpinilla@brandeis.edu"},
{team:0, name:"Qin, Yanan",	email:"	qyn9588@brandeis.edu"},
{team:0, name:"Raphael, Sam",	email:"	sraph@brandeis.edu"},
{team:0, name:"Reddy",	email:"Khan, Karishma	kreddykhan@brandeis.edu"},
{team:0, name:"Rios, Jarrett",	email:"	jrios@brandeis.edu"},
{team:0, name:"Rock, Danielle",	email:"	drock26@brandeis.edu"},
{team:0, name:"Ruiz, Julie",	email:"	jr1740@brandeis.edu"},
{team:0, name:"Rzaev, Darhan",	email:"	darhanrzaev@brandeis.edu"},
{team:0, name:"Sahay, Prakhar",	email:"	prakhar@brandeis.edu"},
{team:0, name:"Sax, Sigal",	email:"	siggy819@brandeis.edu"},
{team:0, name:"Shulman, Stephany",	email:"steshu07@brandeis.edu"},
{team:0, name:"Small, Rhea",	email:"	rheasjam@brandeis.edu"},
{team:0, name:"Song, Ruihua",	email:"	ruihuasong@brandeis.edu"},
{team:0, name:"Soohoo, Jamie",	email:"	soohooj@brandeis.edu"},
{team:29, name:"Sun, Haotian",	email:"	htsun1993@brandeis.edu"},
{team:0, name:"Sun, Jerry",	email:"	boyuan@brandeis.edu"},
{team:0, name:"Sustiel, Zachary",	email:"sustielz@brandeis.edu"},
{team:0, name:"Tjahjadi, Jonas",	email:"	jtjahjad15@brandeis.edu"},
{team:0, name:"Torres, Elmer",	email:"	elmer0216@brandeis.edu"},
{team:0, name:"Trankiem, Amy",	email:"	trankiem@brandeis.edu"},
{team:0, name:"Wang, Kay",	email:"junke@brandeis.edu"},
{team:0, name:"Wang, Rantong",	email:"daa7923@brandeis.edu"},
{team:0, name:"Wang, Xinyue",	email:"xywang19@brandeis.edu"},
{team:0, name:"Wang, Yirong",	email:"shirleyw@brandeis.edu"},
{team:0, name:"Wang, Ziqi",	email:"wangziqi@brandeis.edu"},
{team:0, name:"Weinberg, Ben",	email:"bweinberg@brandeis.edu"},
{team:0, name:"Weld, Charlie",	email:"cweld@brandeis.edu"},
{team:0, name:"Wu, Yangyang",	email:"wuzh@brandeis.edu"},
{team:0, name:"Xiong, Shuao",	email:"seanxiong@brandeis.edu"},
{team:0, name:"Yahna, Gavin",	email:"gavinyahna@brandeis.edu"},
{team:0, name:"Yao, Mingyuan",	email:"monkyao@brandeis.edu"},
{team:0, name:"Yao, Xin",	email:"xyao01@brandeis.edu"},
{team:0, name:"Ye, Yujia",	email:"yyj@brandeis.edu"},
{team:0, name:"Zhu, Christine",	email:"zhuc18@brandeis.edu"},
{team:10, name:"Zhu, Mengdi",	email:"monica92@brandeis.edu"},
{team:0, name:"Zhu, Minghan",	email:"minghanzhu@brandeis.edu"},
{team:0, name:"Zhu, Victor",	email:"telandis@brandeis.edu"},
{team:0, name:"Zhuang, Austin",	email:"austinzxp@brandeis.edu"},
{team:5, name:"Zou, Weitao",	email:"zouwt@brandeis.edu"}
];

Meteor.startup(function(){
  if (Teams.find().count()==0){
		console.log("loading in teamdata");
		teams.forEach(function(s){Teams.insert(s)});
		members.forEach(function(s){Members.insert(s)});
	}

	if (Pokedex.find().count()==0){
		console.log("Importing Pokedex to db")

			 var data = JSON.parse(Assets.getText(
				 "Pokemon-DB-master/pokedex.json"));
			 console.log("data length = "+data.length);

			 data.forEach(function (item, index, array) {
				 //console.log(index+" "+JSON.stringify(item));
					 Pokedex.insert(item);
			 })
			 console.log("Pokedex imported");
	};

// this is very insecure, but helpful for development
	Meteor.publish('userList', function (){
  return Meteor.users.find({});
});

});
